import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from '@/app/NavBar';
import Footer from '@/app/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Leyton Bostre | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body style={inter.style} className="flex flex-col">
                <NavBar/>
                {children}
                <Footer/>
            </body>
        </html>
    );
}
